Linux and macOS support in UpdateChecker
ParadoxGameConverters/Fronter pull request #99
Opened 2021-12-19 15:16 UTC by IhateTrains

2021-12-19 15:34 UTC, IhateTrains commented
OK, it builds now.

2021-12-19 23:21 UTC, Idhrendur requested changes
Because we're getting updates from dependabot, you need to be more cautious about breaking changes. Find a way to make it support both naming systems, then we can all update to this. Each converter can then update to the new naming scheme (as you're trying to introduce this change, it'd be best if you did those updates). Once all are in place, you can remove the old naming scheme.

2021-12-20 11:15 UTC, IhateTrains commented
> Because we're getting updates from dependabot, you need to be more cautious about breaking changes. Find a way to make it support both naming systems, then we can all update to this. Each converter can then update to the new naming scheme (as you're trying to introduce this change, it'd be best if you did those updates). Once all are in place, you can remove the old naming scheme.

I can update the naming scheme across the converters, it's trivial.
I don't think the transitional period is needed, though. If we update the naming scheme in all converters **before** merging this PR, updates will still work seamlessly, as currently any .zip artifact is considered a release archive.

After updating Fronter all will also continue to work, as release archives will be correctly named by that time.

I know our release routines are quite different, so please correct me if I'm missing something.

2021-12-21 02:35 UTC, Idhrendur commented
> If we update the naming scheme in all converters **before** merging this PR, updates will still work seamlessly, as currently any .zip artifact is considered a release archive, regardless the name.

Ah, that's the trick I was missing. Yeah, if you'll go ahead and update those before merging this that'd be perfect.

2021-12-21 02:35 UTC, Idhrendur approved these changes

2021-12-21 15:18 UTC, Idhrendur approved these changes

2022-01-07 21:13 UTC, merged